### ISSUE TITLE
Add orjson.OPT_SERIALIZE_NUMPY to Handle Numpy Serialization in quixstreams

### ISSUE THREAD

**Issue by cale-vdw** [quixai/quix-streams#372]
Problem Statement

During the processing of windowed data transformations in the quixstreams library, numpy float values (numpy.float64) are returned when using a custom reducer function. This leads to serialization errors because the current configuration of orjson used in quixstreams does not support numpy types by default. This issue specifically occurs during windowing where numpy floats are generated and need to be serialized. Below is the stack trace illustrating the error:

```
Traceback (most recent call last):
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/serialization.py", line 21, in serialize
    return dumps(value)
           ^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/utils/json.py", line 15, in dumps
    return orjson.dumps(value, option=_ORJSON_OPTIONS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: numpy.float64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/app.py", line 694, in _process_message
    context.run(dataframe_composed, row.value)
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 239, in wrapper
    return outer_func(inner_func(v))
                      ^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 239, in wrapper
    return outer_func(inner_func(v))
                      ^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 239, in wrapper
    return outer_func(inner_func(v))
                      ^^^^^^^^^^^^^
  [Previous line repeated 6 more times]
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 100, in wrapper
    return list(func(value))
                ^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/time_based.py", line 214, in wrapper
    return func(value, transaction.state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/time_based.py", line 123, in <lambda>
    lambda value, state, process_window=self.process_window: process_window(
                                                             ^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/time_based.py", line 75, in process_window
    aggregated = self._aggregate_func(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/definitions.py", line 205, in func
    state.update_window(
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/windowed/state.py", line 49, in update_window
    return self._transaction.update_window(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/windowed/transaction.py", line 61, in update_window
    self.set(key=key, value=value)
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/transaction.py", line 66, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/transaction.py", line 217, in set
    value_serialized = self._serialize_value(value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/transaction.py", line 351, in _serialize_value
    return serialize(value, dumps=self._dumps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/serialization.py", line 23, in serialize
    raise StateSerializationError(f'Failed to serialize value: "{value}"') from exc
quixstreams.state.rocksdb.exceptions.StateSerializationError: Failed to serialize value: "{'tenant': 'Big Engine Blocks', 'device': 'default', 'datasource': 'some-datasource', 'source_parameter': 'some.param.name', 'timestamp': '2024-05-24T11:33:42.174238+02:00', 'data_numeric': -7.195723749538281, 'parameter': 'big-engine-blocks.default.some-datasource.some.param.name', '_window_values': [-7.496866843343062, -6.894580655733501], '_window_timestamps': ['2024-05-24T11:33:42.071744+02:00', '2024-05-24T11:33:42.174238+02:00']}"
Traceback (most recent call last):
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/serialization.py", line 21, in serialize
    return dumps(value)
           ^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/utils/json.py", line 15, in dumps
    return orjson.dumps(value, option=_ORJSON_OPTIONS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: numpy.float64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/calevanderwesthuizen/Documents/launchpad/scripts/test_pipelines.py", line 78, in <module>
    main(config)
  File "/Users/calevanderwesthuizen/Documents/launchpad/scripts/test_pipelines.py", line 64, in main
    app.run(df)
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/app.py", line 797, in run
    self._process_message(dataframe_composed, start_state_transaction)
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/app.py", line 694, in _process_message
    context.run(dataframe_composed, row.value)
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 239, in wrapper
    return outer_func(inner_func(v))
                      ^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 239, in wrapper
    return outer_func(inner_func(v))
                      ^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 239, in wrapper
    return outer_func(inner_func(v))
                      ^^^^^^^^^^^^^
  [Previous line repeated 6 more times]
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/core/stream/functions.py", line 100, in wrapper
    return list(func(value))
                ^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/time_based.py", line 214, in wrapper
    return func(value, transaction.state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/time_based.py", line 123, in <lambda>
    lambda value, state, process_window=self.process_window: process_window(
                                                             ^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/time_based.py", line 75, in process_window
    aggregated = self._aggregate_func(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/dataframe/windows/definitions.py", line 205, in func
    state.update_window(
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/windowed/state.py", line 49, in update_window
    return self._transaction.update_window(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/windowed/transaction.py", line 61, in update_window
    self.set(key=key, value=value)
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/transaction.py", line 66, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/transaction.py", line 217, in set
    value_serialized = self._serialize_value(value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/calevanderwesthuizen/Documents/launchpad/venv/lib/python3.12/site-packages/quixstreams/state/rocksdb/transaction.py", line 351, in _serialize_value
    return serialize(value, dumps=self._dumps)
```

Quixstreams version:
2.4.2

Question:
Is there a specific reason why support for numpy values has not been included in the quixstreams/utils/json.py configuration for orjson? 

Proposed Solution:
To resolve this issue and improve the robustness of the serialization process, I recommend adding orjson.OPT_SERIALIZE_NUMPY to the _ORJSON_OPTIONS in the quixstreams/utils/json.py file. This change would allow orjson to handle numpy data types without additional custom serialization logic.

Here’s the recommended modification to the quixstreams/utils/json.py file:
```
import orjson

_ORJSON_OPTIONS = (
    orjson.OPT_PASSTHROUGH_DATETIME |
    orjson.OPT_PASSTHROUGH_DATACLASS |
    orjson.OPT_SERIALIZE_NUMPY  # Add this line to support numpy serialization
)
```

**Comment by ghost** [comment]
Hi @cale-vdw , 
Thanks for taking the time to report this issue!
Much appreciated.

To answer your question:
> Question:
Is there a specific reason why support for numpy values has not been included in the quixstreams/utils/json.py configuration for orjson?


Yes. The main reason behind not supporting types like `numpy.float64` is that when they are deserialized back , they will be converted to simple `float`s instead of the initial `float64`.

Here's a quick example:
```
In [12]: number = np.float64(123.123)

In [13]: number_serialized = orjson.dumps(number, option=orjson.OPT_SERIALIZE_NUMPY)

In [14]: number_serialized
Out[14]: b'123.123'

In [15]: number_deserialized = orjson.loads(number_serialized)

In [16]: type(number_deserialized)
Out[16]: float
```

In this case, the downstream code expecting the variable to be of type `numpy.float64` may receive a plain `float`  instead from the state.

That's why we decided to minimize such implicit conversions as much as possible.

**Comment by cale-vdw** [comment]
Thanks @daniil-quix I understand your argument. Can you please give an example of code that would crash that expects a `numpy.float64` but instead receives a python float?

**Comment by cale-vdw** [comment]
@daniil-quix All I can think of is when an attribute of the numpy float is called like `python_float.dumps()` which would crash. Can you maybe think of an alternative method to allow serialization of numpy values as an input argument into the quixstreams API that would remove the need to explicitly cast all output values of custom reducers to a python float?

**Comment by ghost** [comment]
@cale-vdw 
Unfortunately, it is relevant not only for `float64` but all other numpy types as well.

For example:
```
In [47]: number_f32 = np.float32(1231.12312312312323231)

In [48]: number_f32
Out[48]: 1231.1232

In [49]: orjson.loads(orjson.dumps(number_f32, option=orjson.OPT_SERIALIZE_NUMPY)) == number_f32
Out[49]: False
````

As you see, the deserialized value is not equal to the original one.

Similar things may happen with `numpy.array` and other types.

The point is if we have `OPT_SERIALIZE_NUMPY` enabled by default, the original value may silently change without you noticing it. 
Even if the code doesn't crash, it may lead to unexpected results, and it's impossible to foresee all the outcomes.
So we think it's safer to manually handle the conversion in such cases.

There are at least two options for how you can work this around:
1. Convert numpy values to plain Python and back manually during processing (like you do).
2. Provide custom State serialization to the `Application`:

```
from quixstreams import Application
from quixstreams.state.rocksdb import RocksDBOptions

# Overriding the default State serialization with custom "dumps" and "loads" functions
app = Application(
    rocksdb_options=RocksDBOptions(dumps=lambda value: ..., loads=lambda encoded: ...)
)
```

Using custom `dumps` and `loads` functions, you may encode the data the way you need.
For example, you can pass callables with customized `orjson.loads` and `orjson.dumps` to fit your case.

**Note:** 
It will change the SerDes for the whole state in this Application.
If you want to change it later, the already recorded data may become unreadable.
